apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: gha-runner-scale-set-controller
  includeCRDs: true
  releaseName: gha-runner-scale-set-controller
  namespace: actions-runner-controller
  version: 0.11.0
  repo: oci://ghcr.io/actions/actions-runner-controller-charts
